### ISSUE TITLE
Data format: chains of things vs lists of things

### ISSUE THREAD

**Issue by kurtseifried** [cloudsecurityalliance/gsd-database#2205]
So some vulnerability "Types" are a chain of vulnerabilities (e.g. XSS combined with CSRF or whatever). Some are multiple discrete vulnerability types. We need to figure out how to best indicate chains otherwise people may assume they are a list. Thoughts/comments?

example: https://github.com/cloudsecurityalliance/gsd-database/pull/1904

**Comment by athix** [comment]
Could have the key make it explicit that it's a chain? Also could use arrows / chevrons to indicate direction of the chain.

e.g.
```json
{
  "vulnerability_chain": "CWE-502 > CWE-400 > CWE-20"
}
```

**Comment by raphaelahrens** [comment]
JSON arrays must be ordered by design. 

>  An array is an ordered sequence of zero or more values.

https://www.rfc-editor.org/rfc/rfc7159.html#section-1

So only by using a strange lib or if the program wants to sorts them could this be a problem.

A chain could also be represented by an object with numeric indexes.

```
{
  "vulnerability_type": {
    "1": "CWE-502",
    "2": "CWE-400",
    "3": "CWE-20"
  }
}
```

But this means when reading the data in, the order needs to be handled manually and this sounds quite annoying and it needs to be checked if a key was used multiple times.

Another way to deal with this could be, that the vulnerability field could be a list of lists/strings.
With the main list meaning OR and the lower lists meaning AND.

```
{
  "vulnerability_type": [
    [ "CWE-502",  "CWE-400", "CWE-20" ],
    "CWE-117"
  ]
}
```
 
The idea of @athix is a more space efficient solution, but requires manual string parsing.
So when you decide to use this consider adding a special character/string in front of a chain. 
This makes parsing these strings much simpler, since only the first characters needs to be compared to check if it is a chain.
Then the `_chain` addition could even be removed. Maybe the link/chain-emoji (:link:) is a good choice, since it is unlikely to be in a CWE. :smile:  

```
{
  "vulnerability_type": ["🔗CWE-502->CWE-400->CWE-20", "CWE-117"]
}
```

This could be combined with the list of lists by having chains start with a special string.
With both approaches the OR-list could be dropped when not needed.

```
{
  "vulnerability_type":   [ "🔗",  "CWE-502",  "CWE-400", "CWE-20" ]
}
{
  "vulnerability_type":   "🔗CWE-502->CWE-400->CWE-20"
}
```

To remove the need for magic values inside the list an object can be used with the `🔗` key.

```
{
  "vulnerability_type":  {"🔗": [ "CWE-502",  "CWE-400", "CWE-20" ]}
}
```

**Comment by kurtseifried** [comment]
Some additional problems: 

What do we do if no CWE exists?
What do we do if an identifier includes ->, I would suggest we don't rely upon magic characters like -> but instead format it. as a list or whatever (dict with "1":"foo", "2":"bar" for example to ensure they don't get mixed up?). 
Also if it's a chain of vulns we should probably break it up into separate GSDs.

**Comment by raphaelahrens** [comment]
> What do we do if no CWE exists? 

Why can't you not just define one?

In addition I also  would be interested to know if a GSD entry can be a vulnerability type.
For example the JWT standard has the flaw that the sender of an JWT can choose the algorithm(for example described in  GSD-2015-9235 for jsonwebtoken), which in my opinion is a vulnerability of the standard not only a single implementation.
And as a developer I usually choose the standards before the libs, so I see a value in information about vulnerabilities in standards. But as far as I know there is no proper database for this kind of data.

And so I would like to see a GSD for JWTs None algorithm and the miss use of HS* and then you could use this GSD as a vulnerability type for libs that implement JWT, with these flaws.
I know that @kurtseifried  already ask about GSD for standards, but I don't know if there had been a decision.

Any way if a GSD can be a value for '.GSD.vulnerability_type' this would reduce the number of cases where there is no CWE and also make it possible to create new types.

The question then would be can all GSDs be vulnerability type or only some and I guess yes. Since some vulnerabilities are direct results of using other vulnerable software.

So then there is the case where there is a new vulnerability which has no CWE and no GSD that matches.
You could just leave it empty since this must be a new kind of problem which to understand you will need to read the description of the problem anyway. A new CWE would not make sense since this entry is the sole vulnerability for that type.

Only if there are more then one which have a common root cause, then one can think about a new CWE and then it makes sense to define a new one.

So the problem would be how do you track the untyped vulnerabilities and give them types?

Sorry for this long ramble I'm sitting on that though for a while and got triggered.

**Comment by kurtseifried** [comment]
> > What do we do if no CWE exists?
> 
> Why can't you not just define one?

One comment: it's a long process to get a CWE, you submit it, MITRE gets back to you (in my case after 2-3 months) and asks for clarification, you reply, I don't know what happens after that.

I say this as someone who sits on the CWE board: https://cwe.mitre.org/about/board.html

**Comment by raphaelahrens** [comment]
Sorry I didn't meant a new CWE but a new type.

**Comment by kurtseifried** [comment]
> Sorry I didn't meant a new CWE but a new type.

Sorry, a new type of what? CWE is "types" of vulnerabilities, are you referring to something else?

**Comment by raphaelahrens** [comment]
I mean with new type  a new classification or type of vulnerabilities, exactly like the outcome of the CWE process.

But you could have publish your CWE draft 2-3 month ago, others could have used it.
Even if it would be rejected it would still be useful to others.
They could see why it failed, they could see that someone already had that same idea, they might know how to improve it.

So what I mean is someone can publish a new type and publish it outside of the world of CWE and it could be useful.

For the GSD it would have little impact

1. the type/category is wrong then it could be removed/replace, which I guess is also true for CWEs.
2. If the proposal is excepted it can be renamed to the CWE.
3. If it is rejected it might be wrong(see 1.), if it is not wrong then the CWE process is wrong and it could still be used.

An issue I see is the problem of link rot, which is already a problem with other resources.

I say this as nobody, but I don't want to steal your time with my thoughts so feel free to say if I do.

**Comment by kurtseifried** [comment]
Publishing our draft CWE's is in the plan, part of this is working out how to most effectively do this. I'm also trying to fix this at a higher level, e.g. CWE itself. 

If you'd actually like to help move these ideas forwards, that'd be great, as all writers know, ideas are easy, writing/programming/execution is the hard work.

**Comment by kurtseifried** [comment]
closing for now
