### ISSUE TITLE
paths to json are not deterministic (or too convoluted)

### ISSUE THREAD

**Issue by chrisdlangton** [cloudsecurityalliance/gsd-database#2219]
Why
-----
Getting the best JSON data for CVE-2021-1000 should be as easy as replacing 'CVE' with 'GSD'.
True?
Well yes, but no it's not in practice.

Problem
-----
The path is fairly approachable on the surface;
`gsd-database/raw/main/<year>/<shard>/<CVE_ref>.json`

So for `CVE-2021-1000000` it would be `gsd-database/raw/main/2021/1xxx/GSD-2021-1000000.json` right?

Wrong

It's actually `gsd-database/raw/main/2021/1000xxx/GSD-2021-1000000.json` and `gsd-database/raw/main/2021/1xxx/GSD-2021-1000000.json` is an entirely separate `CVE-2021-1000`.

i.e. the programmatic approach to build the path has an edge case, it seems arbitrary or it requires a overly complex rule set of string manipulation starting with `CVE-2021-1000000` to transform into `2021/1000xxx/GSD-2021-1000000` which would be a different set of rule that apply to starting with `CVE-2021-1000` and arriving at `2021/1xxx/GSD-2021-1000` while not arriving at `2021/1xxx/GSD-2021-1000000` if provided with `CVE-2021-1000000`

It's not 'just replace CVE with GSD'

Should it be fixed?
-----

Which fixing this now would break all automation that relies on the existing convoluted structure, it seems necessary as I am seriously considering ignoring this project simply because I can't reliably/easily get to the data from a CVE ref.

I'm not unique, if I find it so unapproachable that I couldn't be bothered starting to use it, others might too

In fact I thought about 'what would take longer; figure out the reliable string manipulation techniques by reviewing all the data year by year to understand these edge cases OR write this long ticket' and you can guess which was quicker

Fixes
-----
1. Keep paths the same, but add an index.json at the root which is a CVE-xxxx-xxxxxxxxxxxxxx map to the valid path
2. change the path to be a direct, straight-forward, and deterministic translation from CVE to the path needed
3. change nothing about the path and do not add an index lookup, but publish an example for each programming language you expect to support that implements and maintains the rules that ensure lookups are reliable. i.e. if you're rule state a list data structure slice position `0` gives you a path segment for the data partition of `1xxx` then stick to that. Because a rule that states this with other conditions like 'except when the number is greater than 1000, then do some additional step that produces an new value other than `1xxx` with arbitrary length based on how much large it is from 1000' << that kind of rule is crazy, no one wants to write code when to do that when they were sold 'just replace CVE with GSD'..

**Comment by raphaelahrens** [comment]
Sorry if I  misunderstand your problem, but the transformation rule looks quite forward.

```
def gsd_path(cve):
   (_cve, year, num_id) = cve.split('-')
   return f"{year}/{num_id[:-3]}xxx/GSD-{year}-{num_id}"
```
This piece of messy python just takes the numeric ID of the CVE as a string and replaces the last three digits with `x`.

What is also confusing to me is that your example looks like a GSD only entry. So all GSD entries greater GSD-YYYY-1000000 have no CVE equivalent, as far as I understand it.
It would have been nice if the GSD only entries would have started with something different, like `G` (GSD-2021-G000000) so that there is less confusion.
But this is a different discussion.

Maybe you can clarify where you have the problem. Especially your last point 

>  if you're rule state a list data structure slice position 0 gives you a path segment for the data partition of 1xxx then stick to 
that. Because a rule that states this with other conditions like 'except when the number is greater than 1000, then do some additional step that produces an new value other than 1xxx with arbitrary length based on how much large it is from 1000' << that kind of rule is crazy, no one wants to write code when to do that when they were sold 'just replace CVE with GSD'..

**Comment by chrisdlangton** [comment]
Let's keep it simpel then

"Just replace CVE with GSD"

is the project moto, I can't say how many times that's been used.

And it's simply not true.

If that transform is to remain, stop saying that phrase

**Comment by joshbressers** [comment]
We are copying how the cvelist shards the data, it's sort of weird, but 🤷 
You can see this here
https://github.com/CVEProject/cvelist/tree/master/2019

The json is bucketed into groups of 1000 files (github doesn't like more than 1000 files in a directory).

Long term, I hope this is all just an API, but for the moment, this is how we decided to do it for the sake of consistency

**Comment by kurtseifried** [comment]
Just a note I stood up the old API to access the files, added to the README (pending merge https://github.com/cloudsecurityalliance/gsd-database/pull/2224):

2. To get a single GSD entry simply use the raw API at https://raw.globalsecuritydatabase.org/GSD-YEAR-NUMBER e.g.https://raw.globalsecuritydatabase.org/GSD-2022-1000000 this will redirect you to the JSON file for that entry if it exists. Please note it does not check if the entry exists or not, it simply redirects if the GSD ID is well formed.

Hope this helps.

**Comment by kurtseifried** [comment]
Also speaking of transforms:

https://github.com/cloudsecurityalliance/gsd-tools/blob/main/cloudflare-workers/gsd-raw-file.js

  const GSDIDExtRegExp = new RegExp(/(GSD-[1-2][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]+)$/)

  if (GSDIDExtRegExp.test(pathname)) {
    var IDData = pathname.split("-")
    var DirRegExp = new RegExp(/([0-9][0-9][0-9])$/)
    var dirName = IDData[2].replace(DirRegExp, "xxx");
    const destinationURL = baseGSD + IDData[1] + "/" + dirName + pathname + ".json"
    return Response.redirect(destinationURL, statusCode)
  }

**Comment by kurtseifried** [comment]
> What is also confusing to me is that your example looks like a GSD only entry. So all GSD entries greater GSD-YYYY-1000000 have no CVE equivalent, as far as I understand it. It would have been nice if the GSD only entries would have started with something different, like `G` (GSD-2021-G000000) so that there is less confusion. But this is a different discussion.

GSD is a superset of security data, it's more than just CVE/NVD/etc. So some GSD entries will have directly corresponding CVE data, and some will not. This of course can change, e.g. we may assign a GSD first for a Linux Kernel issue that CVE later picks up and assigns a CVE.  In general, it's simple, if a GSD has a direct CVE mapping then you'll see something like:

```
{
    "GSD": {
        "alias": "CVE-2021-0001",
```

This also will apply for other identifiers as more data comes in and is published. If you see a GSD that needs such a mapping added just file an issue/do a PR so it can get updated.

**Comment by raphaelahrens** [comment]
So the mapping of CVE to GSD was just a side effect of "forking" the data from CVE and in the future we will see further diversion when GSD updates faster than CVE or will there be double entries?

For example

1. GSD-2030-1000000 gets added
2. CVE-2030-1325 will be added which is equal to GSD-2030-1000000
3. GSD-2030-1000000 gets `GSD.alias` set to CVE-2030-1325

But would there then be a GSD-2030-1325?

I guess this is something you only have to consider when you have to cross that bridge. 
But it would be interesting to know, since this would clarify your position towards CVE and also could be a reason to close this issue. Since "Just replace CVE with GSD" (which I still could not find anywhere) would not be true, at least in the future.

Thanks for the replies and sorry for wasting your time with what ifs.

**Comment by kurtseifried** [comment]
Yes, there would be a GSD-2030-1325 and we would move our data from GSD-2030-1000000 into GSD-2030-1325 for one simple reason: we can update our data easily and add linking information in minutes.

We've already crossed this bridge in the past with the second DWF effort, I can't find the examples but there were several issues we assigned a UVI for and CVE later assigned for.

**Comment by kurtseifried** [comment]
Closing, not actionable, also people can easily use the "raw" API.
